global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'monmouth-l2'
    static_configs:
      - targets: ['host.docker.internal:9001']
    metrics_path: /metrics

  - job_name: 'blockscout'
    static_configs:
      - targets: ['blockscout:4000']
    metrics_path: /metrics
